# Generated by Django 5.2.6 on 2025-09-22 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='書名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可借閱')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='使用者ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借閱日期')),
                ('due_date', models.DateTimeField(verbose_name='應歸還日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='實際歸還日期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='書籍')),
            ],
            options={
                'verbose_name': '借閱紀錄',
                'verbose_name_plural': '借閱紀錄',
            },
        ),
    ]
